apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-multi-gpu
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: accelerate-job-multi
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "accelerate"
          - "launch"
          - "--config_file"
          - "/workspace/multi_gpu_config.yaml"
          - "examples/nlp_example.py"
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /workspace/multi_gpu_config.yaml
          subPath: multi_gpu_config.yaml
        - name: storage-volume
          mountPath: {{ .Values.storage.pvcMountPath }}
      volumes:
      - name: config-volume
        configMap:
          name: accelerate-config
      - name: storage-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
