apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-pvc
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.storage.resources.requests.storage }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
