apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accelerate-pvc
  namespace: default
spec:
  accessModes:
    - {{ .Values.storage.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.resources.requests.storage }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
